### PR TITLE
Hamlet capabilities dependency graph

### PR DESCRIPTION
**Pull request by alexpatel**
https://github.com/Harvard-PRINCESS/Guppy/issues/24

@ming as an example of an empty PR - if you push to this branch again, the PR will reflect the changes (even if you're like midway through code review or something)

### CODE REVIEW

**Comment by alexpatel** [comment]
Also, I've been taught that to distinguish between Pull Requests that are ready/not ready one should not assign anyone to the PR until it is ready to be reviewed/merged.

**Comment by alexpatel** [comment]
Okay, so I have verified that caps.hl in the upstream code matches (roughly, because there are several more hierarchy layers scattered about) the dependency diagram from page 9 of the [capabilities management docs](http://www.barrelfish.org/publications/TN-013-CapabilityManagement.pdf):

screen shot 2017-06-07 at 4 06 49 pm

Next up is to hack together a Python script to grep through caps.hl and output a .dot file.

@mwookawa I am wondering why the code generated by hamlet/FoF (build/x86_64/capabilities/*.c) includes switch cases for all possible architectures - it seems like a lot of wasted instructions that it doesn't just output x86_64 case statements.

**Comment by alexpatel** [comment]
@ming the PNG graph this script generates is [here](https://github.com/Harvard-PRINCESS/barrelfish/blob/9b0e8325cf8f4d4753b5df8429f5b8224a8ef344/capabilities/caps.png) (the aspect ratio of the image is off because the tree is so wide, you'll have to download and zoom in).

script is ready for review - there is some pretty-printing code in HamletBackend.hls that is also amenable to this task + a Haskell graphviz lib, if we want to upstream something

**Comment by alexpatel** [comment]
Also, having two repositories means that none of the issues from Guppy will link over...

**Comment by mwookawa** [comment]
@alexpatel all capabilities defined in the barrelfish codebase can be manipulated by a kernel running on any architecture whose monitor obeys the common interface. hence, hamlet generates capability types and retyping predicates for every architecture on every build. does that answer the switch/case verbosity question?

**Pull request merged**
